//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotMailify.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotMailify.Core.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not specified.
        /// </summary>
        internal static string EmailAddress_AddressNotSpecified {
            get {
                return ResourceManager.GetString("EmailAddress_AddressNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown recipient type specified.
        /// </summary>
        internal static string EmailMessage_UnknownRecipientType {
            get {
                return ResourceManager.GetString("EmailMessage_UnknownRecipientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment stream must be a non-zero length stream that is not closed and can be read.
        /// </summary>
        internal static string EmailMessageWithAttachment_NoContentSpecified {
            get {
                return ResourceManager.GetString("EmailMessageWithAttachment_NoContentSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email provider settings must be specified.
        /// </summary>
        internal static string EmailProvider_SettingsNotSpecified {
            get {
                return ResourceManager.GetString("EmailProvider_SettingsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from value was not specified.
        /// </summary>
        internal static string FromValueNotSpecified {
            get {
                return ResourceManager.GetString("FromValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no recipients specified for message.
        /// </summary>
        internal static string NoEmailRecipientsInMessage {
            get {
                return ResourceManager.GetString("NoEmailRecipientsInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email subject line must not be empty.
        /// </summary>
        internal static string NoSubjectLineInMessage {
            get {
                return ResourceManager.GetString("NoSubjectLineInMessage", resourceCulture);
            }
        }
    }
}
